name: dev_app_broseph
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter_bloc: ^8.1.2
  freezed: ^2.3.3
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  freezed_annotation: ^2.2.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.2

flutter:
  uses-material-design: true
